; generated by Component: ARM Compiler 5.06 update 4 (build 422) Tool: ArmCC [4d3604]
; commandline ArmCC [--c99 --split_sections --debug -c -S -o.\objects\mian.s --depend=.\objects\mian.d --cpu=Cortex-M3 --apcs=interwork -O0 --diag_suppress=9931 -IC:\keil_work\Bootloader_stm32\RTE\Device\STM32F103RC -IC:\keil_work\Bootloader_stm32\RTE\_bootloader -IC:\Keil_v5\ARM\PACK\ARM\CMSIS\5.0.0\CMSIS\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F1xx_DFP\2.1.0\Device\Include -IC:\Keil_v5\ARM\PACK\Keil\STM32F1xx_DFP\2.1.0\Device\StdPeriph_Driver\inc -D__MICROLIB -D__UVISION_VERSION=522 -D_RTE_ -DSTM32F10X_HD --omf_browse=.\objects\mian.crf mian.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.main||, CODE, READONLY, ALIGN=2

main PROC
        PUSH     {r4,lr}
        MOVS     r1,#0
        MOV      r0,#0x8000000
        BL       NVIC_SetVectorTable
        CPSIE    i
        BL       USART1_init
        ADR      r0,|L0.60|
        BL       LOG
        LDR      r0,|L0.76|
        BL       read_falsh_halfword
        MOV      r1,#0xf080
        CMP      r0,r1
        BNE      |L0.44|
        BL       start_app
        B        |L0.56|
|L0.44|
        BL       rece_ack
        B        |L0.54|
|L0.50|
        BL       listener_USART1_data
|L0.54|
        B        |L0.50|
|L0.56|
        MOVS     r0,#0
        POP      {r4,pc}
        ENDP

|L0.60|
        DCB      "bootloader\r\n",0
        DCB      0
        DCB      0
        DCB      0
|L0.76|
        DCD      0x08032800

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "mian.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___6_mian_c_main____REV16|
#line 441 "C:\\Keil_v5\\ARM\\PACK\\ARM\\CMSIS\\5.0.0\\CMSIS\\Include\\cmsis_armcc.h"
|__asm___6_mian_c_main____REV16| PROC
#line 442

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___6_mian_c_main____REVSH|
#line 456
|__asm___6_mian_c_main____REVSH| PROC
#line 457

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___6_mian_c_main____RRX|
#line 643
|__asm___6_mian_c_main____RRX| PROC
#line 644

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

__ARM_use_no_argv EQU 0

        EXPORT __ARM_use_no_argv
        EXPORT main [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT NVIC_SetVectorTable [CODE]
        IMPORT USART1_init [CODE]
        IMPORT LOG [CODE]
        IMPORT read_falsh_halfword [CODE]
        IMPORT start_app [CODE]
        IMPORT rece_ack [CODE]
        IMPORT listener_USART1_data [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,6
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
